" vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker spell:
" TODO:
"       Setup modular vimrc, having separate files for each section of this
"           config
"       Make source come from a non-hardcoded location

" Init {
    source ~/.vim/init.vim
"}
" Colors and Fonts {

    " set Vim-specific sequences for RGB colors
    " This is for fixing the weird lack of True Colours on ST
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

    " Turn on syntax colouring
    syntax on

    " Enable GUI terminal colours
    set termguicolors

    "Use the nord colour scheme if on OSX or use Quantum on linux
    if has("mac")
        colorscheme nord
    else
        "let g:quantum_black=1
        let g:airline_theme='quantum'
        let g:quantum_italics=1
        colorscheme quantum

    endif


"}
" Settings {

    " Tun on numbers and relative numbers
    set number
    set relativenumber

    " 4 soft-tab
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
"    set expandtab

    set foldmethod=syntax
    set foldlevel=4

    " Ignore case unless a capital is explicitly used
    set ignorecase
    set smartcase

    " Change split directions to be more consistent with i3
    set splitbelow
    set splitright

    " List invisible characters
    set list
    set listchars=eol:¬,tab:→\ ,trail:~,extends:»,precedes:«,space:·,nbsp:§

    "Setup highlighting for listchars to make them slightly darker
    if has("mac")
        hi SpecialKey ctermfg=black
    else
        hi SpecialKey ctermfg=grey
    endif

    " Set column colour for long lines
    " TODO: Have this only for lines that exceed the limit
    set colorcolumn=80

    " Match trailing spaces
    match ErrorMsg '\s\+$'

    " Set utf8 as standard encoding and en_US as the standard language
    set encoding=utf8

    " Use Unix as the standard file type
    set fileformats=unix,dos,mac

    " Hide buffers, don't close them
    set hidden
    set showmatch

    " Global flag always applied on regex (save a keypress every search)
    set gdefault

    " Don't redraw while executing macros (good performance config)
    set lazyredraw

    " Deal with swap, backup, and undo files
    call WriteCacheDir("swap")
    set directory=./.vim_data/,~/.cache/vim/swap/,~/.cache/,./,~

    call WriteCacheDir("backup")
    set backupdir=./.vim_data/,~/.cache/vim/backup/,~/.cache/,./,~

    if exists('+undofile')
        call WriteCacheDir("undo")
        set undofile
        set undodir=./.vim_data/,~/.cache/vim/undo/,~/.cache/,./,
    endif

"}
" KeyMapping {
    let mapleader=","

    " Smart way to move between windows
   nnoremap <C-j> <C-w>j
   nnoremap <C-k> <C-w>k
   nnoremap <C-h> <C-w>h
   nnoremap <C-l> <C-w>l

    " Mode binds

    " Run GDiff
   nnoremap <leader>md :Gdiff<cr>

    " Toggle zen mode
   nnoremap <leader>mz :call<space>ZenMode()<cr>

    " Git and diff keybinds

    " Bindings for merging
   nnoremap <leader>dh :diffget //2<cr>
   nnoremap <leader>dt :diffget //3<cr>

    " Git commands
   nnoremap <leader>G :Magit<cr>
   nnoremap <leader>ga :Git add %<cr>
   nnoremap <leader>gA :Git add .<cr>
   nnoremap <leader>gc :Gcommit<cr>
   nnoremap <leader>gs :Gstatus<cr>
   nnoremap <leader>gp :Gpush<cr>
   nnoremap <leader>gu :Gpull<cr>

    " Buffer keybinds
    " Close the git windows
   nnoremap <leader>go :only<cr>

    " Dictionary
    inoremap <expr> <c-x><c-k> fzf#complete('cat /usr/share/dict/words')

    " Pressing \ss will toggle and untoggle spell checking
   nnoremap <leader>ss :setlocal spell!<cr>
    " Spelling correction
   nnoremap <leader>sc z=

    " Add to dictionary
   nnoremap <leader>sa zg
    " Add to session dictionary
   nnoremap <leader>sA zG

    " Add to incorrect word list
   nnoremap <leader>sw zw
    " Add to session incorrect word list
   nnoremap <leader>sW zW


    " Misc

    " Fast saving
   nnoremap <leader>w :w!<cr>

    " Remove the Windows ^M - when the encodings gets messed up
   nnoremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

    " Quickly open a buffer for scribble
   nnoremap <leader>sb :e ~/buffer<cr>

    " Quickly open a markdown buffer for scribble
   nnoremap <leader>sm :e ~/buffer.md<cr>

    " Close the current buffer yet keep the windows intact
   nnoremap <leader>x :BD<cr>

    " Close the current window
   nnoremap <leader>q :q<cr>
   nnoremap <leader>Q :qa<cr>
   nnoremap <leader>z :w<cr>:BD<cr>
   nnoremap <leader>Z :w<cr>:qa<cr>

    " Toggle paste mode on and off
   nnoremap <leader>pp :setlocal paste!<cr>

    "Plugin keymaps
    nnoremap <leader>B :Buffers<cr>
    nnoremap <leader>F :FZF<space>
    nnoremap <leader>S :Snippets<cr>
    nnoremap <leader>ff :FZF<cr>
    nnoremap <leader>fl :Lines<cr>
    nnoremap <leader>fb :BLines<cr>
    nnoremap <leader>ft :Tags<cr>
    nnoremap <leader>fr :History<cr>
    nnoremap <leader>fh :Helptags<cr>
    nnoremap <leader>f: :History:<cr>
    nnoremap <leader>f/ :History/<cr>
    nnoremap <leader>fg :GFiles<cr>
    nnoremap <leader>fs :GFiles?<cr>
    nnoremap <leader>fc :Commits<cr>
    nnoremap <leader>fC :Commands<cr>
    nnoremap <leader>a :Ag<cr>
    nnoremap <leader>fa :Ag<space>

""}
" Plugin Settings {
    "let g:rainbow_active = 1

    if has("mac")
        " If installed using Homebrew
        set rtp+=/usr/local/opt/fzf

        " If installed using git
        set rtp+=~/.fzf
    endif

    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*

    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0

    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_guide_size = 1

    let g:UltiSnipsJumpForwardTrigger="<c-j>"
    let g:UltiSnipsJumpBackwardTrigger="<c-k>"
    let g:UltiSnipsExpandTrigger="<tab>"

    let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']
"}
" Per file settings {
    autocmd FileType haskell,puppet,ruby,yaml,markdown setlocal expandtab shiftwidth=2 softtabstop=2

    " File specific keymaps
    " TODO: Replace these with snippits
    autocmd FileType markdown source ~/.vim/keymaps/markdown.vim
    autocmd FileType java source ~/.vim/keymaps/java.vim
"}
" Commands {
    " :W sudo saves the file
    command W w !sudo tee % > /dev/null
"}
" Netrw settings {
    let g:netrw_banner = 0
    let g:netrw_liststyle = 3
    let g:netrw_browse_split = 4
    let g:netrw_altv = 1
    let g:netrw_winsize = 12
    augroup ProjectDrawer
        autocmd!
        autocmd VimEnter * :Vexplore | :set winfixwidth | :winc l
    augroup END


    " To avoid overwriting the netrw buffer with some other buffer, we should
    " change window before executing
    augroup NetrwMaps
        autocmd FileType netrw nnoremap <buffer> <leader>B :winc w<cr>:Buffers<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>F :winc w<cr>:FZF<space>
        autocmd FileType netrw nnoremap <buffer> <leader>ff :winc w<cr>:FZF<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fl :winc w<cr>:Lines<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fb :winc w<cr>:BLines<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>ft :winc w<cr>:Tags<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fr :winc w<cr>:History<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fh :winc w<cr>:Helptags<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>f: :winc w<cr>:History:<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>f/ :winc w<cr>:History/<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fg :winc w<cr>:GFiles<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fs :winc w<cr>:GFiles?<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fc :winc w<cr>:Commits<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fC :winc w<cr>:Commands<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>a :winc w<cr>:Ag<cr>
        autocmd FileType netrw nnoremap <buffer> <leader>fa :winc w<cr>:Ag<space>
        autocmd FileType netrw nnoremap <buffer> - <plug>VinegarUp
    augroup END
"}
