# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install
#

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

export PATH

export SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
export VISUAL=nvim
export EDITOR=nvim

source <("/usr/bin/starship" init zsh --print-full-init)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(fasd --init posix-alias zsh-hook 2>/dev/null)"

if [ ${TERM} = "xterm-kitty" ]; then
	alias sssh='SSHPASS="$(tspintotp)" sshpass -e kitty + kitten ssh'
	alias ssh="kitty +kitten ssh"
fi

alias rm='trash'
alias vim='nvim'
alias v='vim'
alias e='vim'

alias cdtmp='cd $(mktemp -d)'


fpath=( ~/.config/zsh/functions/ "${fpath[@]}" )
autoload -Uz $fpath[1]/*(.:t)
